image: node:12.16.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: CI
          caches:
              - node
          script:
              - npm install
              - npm run build
  branches:
    master:
      - step:
          name: Preparing for deployment
          deployment: production
          script:
              - npm install
              - npm run build
              - tar czfv application.tgz dist static.json
          artifacts:
            - application.tgz
      - step:
          name: Deploy to production
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: fbzhjzwipk
                ZIP_FILE: "application.tgz"
