image: node:12.16.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: CI
          caches:
              - node
          script:
              - npm install
              - npm run lint
              - npm run test-backend
              - npm run test-frontend
              - npx codecov -t $CODECOV_TOKEN
              - npm run build
    release/*:
      - step:
          name: Release CI
          script:
              - npm ci
              - npm run lint
              - npm run test-frontend
              - npm run test-backend
              - npx codecov -t $CODECOV_TOKEN
              - npm run build
  branches:
    dev:
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/xmontosmwn.git HEAD:master
    master:
      - step:
          name: Deploy to production
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/nztzkuyqzx.git HEAD:master
