image: node:12.16.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: CI
          caches:
              - node
          script:
              - npm install
              - npm run lint
              - npm run test
              - npm run build
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/fbzhjzwipk.git HEAD:master
