export const FETCH_USER_IDENTITY_REQUEST = 'FETCH_USER_IDENTITY_REQUEST';
export const FETCH_USER_IDENTITY_SUCCESS = 'FETCH_USER_IDENTITY_SUCCESS';
export const FETCH_USER_IDENTITY_FAILED = 'FETCH_USER_IDENTITY_FAILED';

export const SET_TOKEN = 'SET_TOKEN';

export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
