import axios, { AxiosRequestConfig, AxiosInstance } from 'axios';

/**
 * Axios / Network related configurations
 */

/** Retrieve token cookie generated by backend */
const [cookieCsrfToken = ''] = document.cookie.split(';').filter((v) => /^xsrf-token=/.test(v.trim()));
const csrfToken = cookieCsrfToken.trim().replace('xsrf-token=', '');

const DEFAULT_API_BASE_URL = `${process.env.API_BASE_URL}/api`;
const API_BASE_URL = process.env.NODE_ENV === 'development' && process.env.API_BASE_URL
  ? DEFAULT_API_BASE_URL
  : '/api';

/**
 * Creates a base axios instance
 */
const api = axios.create({
  baseURL: API_BASE_URL,
  responseType: 'json',
  xsrfHeaderName: 'X-XSRF-TOKEN',
  headers: {
    'X-XSRF-TOKEN': csrfToken,
  },
});

/**
 * Creates a modifiable axios instance
 * @param baseURL The base URL the network request will be sent
 * @param headers Could be any passable header values
 */
export const apiConfig = ({
  baseURL = API_BASE_URL, headers,
}: AxiosRequestConfig): AxiosInstance => axios.create({
  baseURL,
  xsrfHeaderName: 'X-XSRF-TOKEN',
  headers: {
    ...headers,
    'X-XSRF-TOKEN': csrfToken,
  },
});

export default api;
